# Generated by Django 5.0.4 on 2024-06-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cutting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuttingpattern",
            name="repetition",
        ),
        migrations.RemoveField(
            model_name="cuttingpattern",
            name="request",
        ),
        migrations.CreateModel(
            name="CuttingPatternUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repetition", models.IntegerField()),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="cutting.cuttingpattern",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_usages",
                        to="cutting.cuttingrequest",
                    ),
                ),
            ],
        ),
    ]
