# Generated by Django 5.0.4 on 2024-06-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cutting", "0002_remove_cuttingpattern_repetition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingpattern",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
